/**
 * Textos del panel que Strapi 5.56 aún no trae en español (se ven en inglés aunque el panel esté
 * en español). Solo los que ve un editor o el Super Admin del Foro: inicio, gestor de contenido,
 * biblioteca de medios, sesiones y errores. Las claves de un plugin llevan su prefijo
 * ("content-manager.", "upload.", "email."). Se dejan fuera las pantallas de planes de pago,
 * IA y tutoriales del constructor de tipos, que en este proyecto no aparecen.
 */
const admin: Record<string, string> = {
  'search.placeholder': 'Buscar',
  'HomePage.widget.no-permissions': 'No tienes permiso para ver esta tarjeta',
  'HomePage.addWidget.title': 'Agregar tarjeta',
  'HomePage.addWidget.noWidgetsAvailable': 'No hay tarjetas para agregar',
  'HomePage.addWidget.button': 'Agregar tarjeta',
  'HomePage.widget.delete': 'Quitar',
  'HomePage.widget.drag': 'Arrastra para moverla',
  'app.error.chunk.message':
    'El panel no pudo cargar esta pantalla. Suele pasar si el servidor está arrancando o se cortó la conexión. Recarga la página para intentarlo de nuevo.',
  'app.error.chunk.reload': 'Recargar la página',
  'app.error.chunk.title': 'No se pudo cargar esta pantalla',
  'app.components.NpsSurvey.select-rating': 'Elige una calificación',
  'app.components.MediaLibraryBanner.button': 'Documentación',
  'app.components.MediaLibraryBanner.button.enabled': 'Leer el artículo',
  'app.components.MediaLibraryBanner.close': 'Cerrar el aviso',
  'app.components.MediaLibraryBanner.intro': 'Nueva biblioteca de medios. ',
  'app.components.MediaLibraryBanner.text': 'Consulta la documentación para cambiar a la nueva.',
  'app.components.MediaLibraryBanner.text.enabled': 'Ya estás usando la versión renovada.',
  'app.components.ToggleCheckbox.enabled-label': 'Activado',
  'app.components.ToggleCheckbox.disabled-label': 'Desactivado',
  'app.session.ended.title': 'La sesión terminó',
  'app.session.ended.unsaved':
    'Tu sesión terminó y no se puede retomar. Los cambios sin guardar se perderán al salir.',
  'app.utils.update-filter': 'Actualizar filtro',
  'app.utils.already-published': 'Ya publicado',
  'app.HeaderLayout.docLink.label': 'Más información en la documentación',
  'components.Input.error.contain.maxBytes': 'La contraseña debe tener menos de 73 bytes',
  'components.Input.error.validation.combobox.invalid': 'El valor elegido no es válido',
  'components.Wysiwyg.blocks.code': 'Código',
  'global.last-change.redo': 'Rehacer el último cambio',
  'global.last-change.undo': 'Deshacer el último cambio',
  'global.last-changes.discard': 'Descartar los últimos cambios',
  'global.more': 'Más',
  'global.sessions.active-devices': 'Dispositivos activos',
  'Settings.sessions.title': 'Dispositivos activos',
  'Settings.sessions.subtitle': 'Los dispositivos y sesiones que tienen tu cuenta abierta ahora.',
  'Settings.sessions.device': 'Dispositivo',
  'Settings.sessions.loginAt': 'Inicio de sesión',
  'Settings.sessions.lastActiveAt': 'Último uso',
  'Settings.sessions.actions': 'Acciones',
  'Settings.sessions.current': 'Este dispositivo',
  'Settings.sessions.unknownDevice': 'Dispositivo desconocido',
  'Settings.sessions.revoke': 'Cerrar sesión',
  'Settings.sessions.revoke.success': 'Sesión cerrada',
  'Settings.sessions.revoke.confirm':
    '¿Seguro que quieres cerrar esta sesión? Ese dispositivo tendrá que volver a iniciar sesión.',
  'Settings.sessions.revoke.confirmCurrent':
    'Es el dispositivo que estás usando: si cierras esta sesión, saldrás del panel.',
  'Settings.sessions.revokeOthers': 'Cerrar sesión en los demás dispositivos',
  'Settings.sessions.revokeOthers.confirm':
    '¿Seguro? Se cerrarán todas las demás sesiones; en este dispositivo sigues dentro.',
  'Settings.sessions.revokeOthers.success': 'Se cerraron las demás sesiones',
  'Settings.sessions.revokeAll': 'Cerrar sesión en todos los dispositivos',
  'Settings.sessions.revokeAll.confirm':
    '¿Seguro? Se cerrarán todas las sesiones, también esta, y tendrás que volver a entrar.',
  'widget.last-activity.link': 'Abrir el registro de actividad',
  'widget.last-activity.no-activity': 'Sin actividad',
  'widget.last-activity.title': 'Actividad reciente',
};

const contentManager: Record<string, string> = {
  'plugin.name': 'Gestor de contenido',
  'actions.open-in-new-tab.label': 'Abrir en una pestaña nueva',
  'actions.copy-documentId.label': 'Copiar el identificador',
  'actions.copy-documentId.success': 'Identificador copiado',
  'components.DynamicZone.unknown-component': 'Componente desconocido',
  'components.DynamicZone.move-up': 'Subir',
  'components.DynamicZone.move-down': 'Bajar',
  'components.RelationInputModal.modal-title': 'Editar la relación',
  'components.RelationInputModal.button-fullpage': 'Ir a la entrada',
  'components.RelationInputModal.confirmation-message':
    'Hay cambios sin guardar. ¿Seguro que quieres cerrar? Se perderán.',
  'bulk-publish.waiting-for-action': 'Esperando una acción',
  'containers.edit.information.documentId.label': 'Identificador',
  'containers.List.statusFilter.draft': 'Borrador (nunca publicado)',
  'containers.List.statusFilter.published': 'Publicado (todos)',
  'containers.List.statusFilter.publishedModified': 'Publicado (con cambios sin publicar)',
  'containers.List.statusFilter.publishedUnmodified': 'Publicado (sin cambios)',
  'containers.list.filters.status': 'Estado',
  'containers.SettingPage.editSettings.relationOpenMode': 'Cómo se abren las relaciones',
  'containers.SettingPage.editSettings.relationOpenMode.description':
    'Elige cómo se abre una entrada relacionada al hacer clic',
  'containers.SettingPage.editSettings.relationOpenMode.modal': 'En una ventana (predeterminado)',
  'containers.SettingPage.editSettings.relationOpenMode.newTab': 'En una pestaña nueva',
  'containers.SettingPage.editSettings.relationOpenMode.page': 'En la misma página',
  'containers.empty-label': 'Sin título',
  'containers.untitled': 'Sin título',
  'permissions.not-allowed.locale': 'No tienes permiso para ver este contenido en ese idioma',
  'popUpWarning.warning.has-draft-m2m-relations.message':
    '{count, plural, one {# entrada enlazada sigue en borrador. Aparecerá en el sitio cuando se publique.} other {# entradas enlazadas siguen en borrador. Aparecerán en el sitio cuando se publiquen.}}',
  'popUpWarning.warning.has-draft-m2m-relations.additional':
    '{count, plural, one {# enlace apunta} other {# enlaces apuntan}} a entradas en borrador que se verán cuando se publiquen.',
  'preview.panel.button-configuration': 'Configurar la vista previa',
  'preview.content.close-editor': 'Cerrar el editor',
  'preview.content.open-editor': 'Abrir el editor',
  'preview.device.select': 'Elige el tipo de dispositivo',
  'preview.device.desktop': 'Computadora',
  'preview.device.mobile': 'Teléfono',
  'preview.info.single-click-hint': 'Doble clic para editar',
  'preview.error.invalid-field-path': 'No se encontró este campo en el documento',
  'preview.error.relations-not-handled': 'Las relaciones aún no se pueden editar aquí.',
  'preview.error.incomplete-strapi-source': 'A este campo le falta información de vista previa',
  'preview.error.different-document': 'Este campo es de otro documento',
  'preview.error.script-failed': 'No se pudo cargar la vista previa en vivo.',
  'relation.create': 'Crear una relación',
  'validation.error.unreadable-required-field':
    'Tus permisos no te dejan ver algunos campos obligatorios. Pide acceso al Super Admin para continuar.',
};

const upload: Record<string, string> = {
  'plugin.name': 'Biblioteca de medios',
  'apiError.FolderContainsUnauthorizedAssetsError':
    'Las carpetas elegidas tienen archivos que no tienes permiso de borrar.',
  'assets.uploaded':
    '{number, plural, one {# archivo subido} other {# archivos subidos}} correctamente',
  'asset-details.title': 'Detalles del archivo',
  'asset-details.description': 'Información y datos del archivo',
  'asset-details.fileInfo': 'Información del archivo',
  'asset-details.error': 'No se pudieron cargar los detalles del archivo.',
  'asset-details.videoNotSupported': 'Tu navegador no puede reproducir este video.',
  'asset-details.size': 'Tamaño',
  'asset-details.dimensions': 'Dimensiones',
  'asset-details.creationDate': 'Fecha de creación',
  'asset-details.lastUpdated': 'Última modificación',
  'asset-details.createdBy': 'Subido por',
  'asset-details.extension': 'Extensión',
  'asset-details.assetId': 'ID del archivo',
  'asset-details.fileName': 'Nombre del archivo',
  'asset-details.caption': 'Pie de foto',
  'asset-details.alternativeText': 'Texto alternativo',
  'asset-details.location': 'Ubicación',
  'asset-details.save': 'Guardar cambios',
  'asset-details.update.success': 'Archivo actualizado',
  'asset-details.update.error': 'No se pudo actualizar el archivo.',
  'asset-details.field.empty': '{label} está vacío.',
  'asset-details.location.root': 'Biblioteca de medios',
  'asset-details.saveChanges': 'Guardar cambios',
  'asset-details.delete.trigger': 'Borrar este archivo',
  'asset-details.delete.title': '¿Borrar este archivo?',
  'asset-details.delete.description':
    'Un archivo borrado no se puede recuperar. Si se está usando, el contenido que lo muestra quedará sin imagen.',
  'asset-details.delete.success': 'Se borró 1 elemento de {folderName}',
  'asset-details.delete.error': 'No se pudo borrar el archivo.',
  'asset-details.delete.loading': 'Borrando el archivo…',
  'asset-details.replace.trigger': 'Reemplazar este archivo',
  'asset-details.replace.title': '¿Reemplazar este archivo?',
  'asset-details.replace.description': 'El archivo actual se sustituirá para siempre.',
  'asset-details.replace.description.ai': 'Después de subirlo se generarán datos nuevos.',
  'asset-details.replace.continue': 'Continuar',
  'asset-details.replace.success': 'Archivo reemplazado.',
  'asset-details.replace.error': 'No se pudo reemplazar el archivo.',
  'asset-details.replace.loading': 'Reemplazando el archivo…',
  'asset-details.copy-link.trigger': 'Copiar enlace',
  'asset-details.copy-link.success': 'Enlace copiado.',
  'asset-details.copy-link.error': 'No se pudo copiar el enlace.',
  'asset-details.download.trigger': 'Descargar',
  'asset-details.download.error': 'No se pudo descargar el archivo.',
  'asset-details.crop.trigger': 'Recortar',
  'asset-details.crop.title': 'Recorte y punto de interés',
  'asset-details.crop.hint':
    'Marca el recorte con el rectángulo. Con el círculo, fija la parte que siempre debe verse.',
  'asset-details.crop.width': 'Ancho (px)',
  'asset-details.crop.height': 'Alto (px)',
  'asset-details.crop.aspect-lock': 'Mantener la proporción',
  'asset-details.crop.focal-point': 'Punto de interés',
  'asset-details.crop.focal-x': 'Punto de interés X (px)',
  'asset-details.crop.focal-y': 'Punto de interés Y (px)',
  'asset-details.crop.focal-x-axis': 'X',
  'asset-details.crop.focal-y-axis': 'Y',
  'asset-details.crop.resize.top-left': 'Cambiar tamaño desde arriba a la izquierda',
  'asset-details.crop.resize.top-right': 'Cambiar tamaño desde arriba a la derecha',
  'asset-details.crop.resize.bottom-left': 'Cambiar tamaño desde abajo a la izquierda',
  'asset-details.crop.resize.bottom-right': 'Cambiar tamaño desde abajo a la derecha',
  'asset-details.crop.export-error': 'No se pudo procesar la imagen recortada.',
  'asset-details.crop.cancel': 'Cancelar',
  'asset-details.crop.save-as-copy': 'Guardar como copia',
  'asset-details.crop.apply': 'Aplicar',
  'asset-details.crop.success': 'Archivo recortado.',
  'asset-details.crop.copy-success': 'Copia creada.',
  'asset-details.crop.error': 'No se pudo recortar el archivo.',
  'asset-details.crop.loading': 'Guardando la copia recortada…',
  'asset-details.noPreview': 'Sin vista previa',
  'upload.progress': 'Progreso de la subida',
  'upload.progress.description': 'Muestra cómo va la subida',
  'upload.progress.failed': 'No se pudo subir',
  'upload.progress.failed.subtitle': 'Intenta subir los archivos de nuevo',
  'upload.progress.success': '¡Subida completa!',
  'upload.progress.success.subtitle':
    '{count, plural, one {# archivo subido} other {# archivos subidos}}',
  'upload.progress.success.subtitle.withErrors': '{successCount} subidos, {errorCount} fallaron',
  'upload.progress.uploading.withCount':
    'Subiendo {total, plural, one {# archivo} other {# archivos}} ({percentage}%)',
  'upload.progress.uploading.indeterminate':
    'Subiendo {total, plural, one {# archivo} other {# archivos}}',
  'upload.progress.uploading-files': 'Subiendo {count, plural, one {# archivo} other {# archivos}}',
  'upload.progress.indicator.in-progress': 'Subida en curso',
  'upload.progress.indicator.complete': 'Subida completa',
  'upload.progress.label': 'Subida',
  'upload.progress.errors.title': 'No se pudieron subir:',
  'upload.progress.cancel': 'Cancelar todo',
  'upload.progress.canceled': 'Subida cancelada',
  'upload.progress.canceled.subtitle': 'Algunos archivos no se subieron',
  'upload.progress.canceled.subtitle.all': 'Se cancelaron todas las subidas',
  'upload.progress.retry': 'Reintentar',
  'upload.progress.file.uploading': 'Subiendo…',
  'upload.progress.file.canceled': 'Cancelado',
  'upload.progress.file.queued': 'En espera',
  'upload.progress.file.uploaded': 'Subido',
  'upload.progress.maximize': 'Agrandar',
  'upload.progress.minimize': 'Minimizar',
  'upload.progress.close': 'Cerrar',
  new: 'Nuevo',
  'control-card.set-focal-point': 'Fijar el punto de interés',
  'control-card.stop-focal-point': 'Cancelar el punto de interés',
  'control-card.reset-focal-point': 'Volver al centro',
  'control-card.save-focal-point': 'Guardar el punto de interés',
  'control-card.more-actions': 'Más acciones',
  'control-card.remove-selection': 'Quitar de la selección',
  'dropzone.upload.message': 'Suelta aquí para subir a',
  'form.input.placeholder.file-caption': 'Escribe el pie de foto',
  'folder.create.title': 'Carpeta nueva',
  'folder.create.title-in': 'Carpeta nueva en {folderName}',
  'folder.form.name.label': 'Nombre de la carpeta',
  'folder.create.submit': 'Crear carpeta',
  'folder.create.form.error.name-required': 'Escribe un nombre',
  'folder.create.form.error.unknown': 'Ocurrió un error al crear la carpeta',
  'folder.create.success': 'Carpeta creada',
  'folder.rename.title': 'Cambiar el nombre de la carpeta',
  'folder.rename.submit': 'Guardar',
  'folder.rename.form.error.unknown': 'Ocurrió un error al cambiar el nombre',
  'folder.rename.success': 'Nombre cambiado',
  'header.content.item-count': '{count, plural, =1 {# elemento} other {# elementos}}',
  'header.search.placeholder': 'Buscar',
  'header.search-results': 'Resultados para «{query}»',
  'header.search-results.count':
    '{numberFolders, plural, one {1 carpeta} other {# carpetas}} - {numberAssets, plural, one {1 archivo} other {# archivos}}',
  'header.search-results.count.assets':
    '{numberAssets, plural, =0 {0 archivos} one {1 archivo} other {# archivos}}',
  'header.search-results.count.folders':
    '{numberFolders, plural, one {1 carpeta} other {# carpetas}}',
  'import-files': 'Subir archivos',
  'import-from-url': 'Subir desde un enlace',
  'input.url.placeholder': 'Vacío',
  'list.assets.error': 'Ocurrió un error al cargar los archivos.',
  'list.empty.title': 'Aún no hay archivos',
  'list.empty.description': 'Empieza subiendo archivos o creando una carpeta.',
  'list.empty.add-assets': 'Agregar archivos',
  'list.filters.trigger': 'Filtrar',
  'list.filters.field.type': 'Tipo',
  'list.filters.field.created': 'Fecha de creación',
  'list.filters.field.updated': 'Última modificación',
  'list.filters.type.folder': 'Carpeta',
  'list.filters.type.picture': 'Imagen',
  'list.filters.type.audio': 'Audio',
  'list.filters.type.video': 'Video',
  'list.filters.type.document': 'Documento',
  'list.filters.preset.1day': 'Hace 1 día',
  'list.filters.preset.3days': 'Hace 3 días',
  'list.filters.preset.1week': 'Hace 1 semana',
  'list.filters.preset.1month': 'Hace 1 mes',
  'list.filters.preset.3months': 'Hace 3 meses',
  'list.filters.preset.6months': 'Hace 6 meses',
  'list.filters.preset.1year': 'Hace 1 año',
  'list.filters.select-date-range': 'Elige un rango de fechas',
  'list.filters.condition.is': 'es',
  'list.filters.condition.is-not': 'no es',
  'list.filters.condition.is-exactly': 'es exactamente',
  'list.filters.condition.within-last': 'en los últimos',
  'list.filters.condition.not-within-last': 'fuera de los últimos',
  'list.filters.remove': 'Quitar el filtro {filter}',
  'list.filters.empty': 'Ningún elemento coincide con los filtros',
  'list.filters.clear': 'Quitar filtros',
  'list.filters.calendar.previous-month': 'Mes anterior',
  'list.filters.calendar.next-month': 'Mes siguiente',
  'list.filters.calendar.label': 'Elige un rango de fechas',
  'list.sort.trigger': 'Orden: {active}',
  'list.sort.section': 'Ordenar',
  'list.sort.oldest-uploads': 'Subidos primero',
  'list.sort.most-recent-updates': 'Modificados recientemente',
  'list.sort.name-asc': 'De la A a la Z',
  'list.sort.name-desc': 'De la Z a la A',
  'list.sort.size-asc': 'Más livianos primero',
  'list.sort.size-desc': 'Más pesados primero',
  'list.sort.folders': 'Carpetas',
  'list.sort.folders-on-top': 'Arriba',
  'list.sort.folders-mixed': 'Mezcladas con los archivos',
  'list.sort.active': '(activo)',
  'list.search.empty.title': 'Sin resultados',
  'list.search.empty.description':
    'Ningún archivo ni carpeta coincide con «{query}». Prueba con otra búsqueda.',
  'list.search.empty.clear': 'Borrar la búsqueda',
  'list.assets.loading-more': 'Cargando más archivos…',
  'list.assets.actions.replace': 'Reemplazar',
  'list.assets.actions.copy-link': 'Copiar enlace',
  'list.assets.actions.download': 'Descargar',
  'list.assets.actions.move': 'Mover a una carpeta',
  'list.assets.actions.delete': 'Borrar',
  'list.folder.actions.copy-link': 'Copiar enlace de la carpeta',
  'list.folder.actions.copy-link.success': 'Enlace de la carpeta copiado.',
  'list.folder.actions.copy-link.error': 'No se pudo copiar el enlace de la carpeta.',
  'list.folder.actions.rename': 'Cambiar el nombre',
  'list.folder.actions.move': 'Mover a una carpeta',
  'list.folder.actions.delete': 'Borrar la carpeta',
  'modal.file-details.focal-point': 'Punto de interés',
  'modal.move.error-label': 'Ocurrió un error al mover los elementos.',
  'dnd.announce.drag-start': 'Tomaste {name}. Suéltalo sobre una carpeta para moverlo.',
  'dnd.announce.invalid-drop': 'No se puede mover a esta carpeta.',
  'dnd.announce.move-failure': 'No se pudo mover. {message}',
  'dnd.announce.cancel': 'Movimiento cancelado.',
  'dnd.overlay.folders': '{count, plural, one {# carpeta} other {# carpetas}}',
  'dnd.overlay.files': '{count, plural, one {# archivo} other {# archivos}}',
  'plugin.home': 'Inicio',
  'settings.section.audio.label': 'Audio',
  'list.table.header.creationDate': 'Fecha de creación',
  'list.table.header.lastModified': 'Última modificación',
  'list.table.header.select-all': 'Seleccionar todo',
  'list.table.row.select': 'Seleccionar {name}',
  'list.table.row.metadata-missing': 'A este archivo le falta pie de foto o texto alternativo.',
  'list.context-menu.label': 'Acciones de la biblioteca',
  'list.bulk-actions.label': 'Acciones en grupo',
  'list.bulk-actions.selected-count':
    '{count, plural, =1 {# elemento seleccionado} other {# elementos seleccionados}}',
  'list.bulk-actions.select-all': 'Seleccionar todo',
  'list.bulk-actions.clear': 'Quitar la selección',
  'list.bulk-actions.move': 'Mover',
  'list.bulk-actions.move.title': 'Mover a',
  'list.bulk-actions.move.location': 'Ubicación',
  'list.bulk-actions.move.no-destination': 'No hay otra carpeta adonde moverlo.',
  'list.bulk-actions.move.load-error': 'No se pudo cargar la lista de carpetas. Intenta de nuevo.',
  'list.bulk-actions.move.submit': 'Mover',
  'list.bulk-actions.move.success':
    '{count, plural, =1 {Se movió # elemento} other {Se movieron # elementos}} de {source} a {destination}',
  'list.bulk-actions.move.success-multiple-sources':
    '{count, plural, =1 {Se movió # elemento} other {Se movieron # elementos}} a {destination}',
  'list.bulk-actions.move.error': 'Ocurrió un error al mover los elementos.',
  'list.bulk-actions.delete': 'Borrar',
  'list.bulk-actions.delete.confirm.title':
    '¿Borrar {count, plural, =1 {# elemento} other {# elementos}}?',
  'list.bulk-actions.delete.confirm.description.are-you-sure':
    '¿Seguro que quieres borrar lo seleccionado?',
  'list.bulk-actions.delete.confirm.description.cant-be-undone':
    'No se puede deshacer. Borrar una carpeta borra todo lo que tiene dentro, y el contenido que use esos archivos quedará sin imagen.',
  'list.bulk-actions.delete.success':
    '{count, plural, =1 {Se borró # elemento} other {Se borraron # elementos}}',
  'list.bulk-actions.delete.error': 'Ocurrió un error al borrar los elementos.',
  'view.switch.label': 'Opciones de vista',
  'view.table': 'Vista de tabla',
  'view.grid': 'Vista de cuadrícula',
  'sidebar.title': 'Biblioteca de medios',
  'sidebar.home': 'Inicio',
  'sidebar.folders': 'Carpetas',
  'sidebar.tree.aria-label': 'Carpetas de la biblioteca',
  'sidebar.tree.expand': 'Abrir {name}',
  'sidebar.tree.no-subfolders': 'La carpeta {name} no tiene subcarpetas',
  'sidebar.tree.collapse': 'Cerrar {name}',
  'sidebar.tree.empty': 'Aún no hay carpetas',
  'sidebar.tree.loading': 'Cargando carpetas…',
  'sidebar.tree.error': 'No se pudieron cargar las carpetas.',
};

const email: Record<string, string> = {
  'Settings.email.plugin.button.verify': 'Probar la conexión',
  'Settings.email.plugin.label.replyToName': 'Nombre para respuestas',
  'Settings.email.plugin.label.senderName': 'Nombre del remitente',
  'Settings.email.plugin.label.verifyConnection': 'Estado de la conexión',
  'Settings.email.plugin.notification.verify.error': 'La conexión falló',
  'Settings.email.plugin.notification.verify.success': 'Conexión verificada',
  'Settings.email.plugin.status.connected': 'Conectado',
  'Settings.email.plugin.status.error': 'Error',
  'Settings.capabilities.title': 'Capacidades del proveedor',
  'Settings.capabilities.subtitle': 'Configuración SMTP actual y funciones activas',
  'Settings.capabilities.label.smtpServer': 'Servidor SMTP',
  'Settings.capabilities.label.encryption': 'Cifrado',
  'Settings.capabilities.label.authType': 'Autenticación',
  'Settings.capabilities.label.poolStatus': 'Estado de las conexiones',
  'Settings.capabilities.label.features': 'Funciones activas',
  'Settings.capabilities.poolStatus.idle': 'En reposo',
  'Settings.capabilities.poolStatus.active': 'Activo',
};

const prefixed = (prefix: string, texts: Record<string, string>) =>
  Object.fromEntries(Object.entries(texts).map(([k, v]) => [`${prefix}.${k}`, v]));

export const TRADUCCIONES_ES: Record<string, string> = {
  ...admin,
  ...prefixed('content-manager', contentManager),
  ...prefixed('upload', upload),
  ...prefixed('email', email),
};
