/**
 * Las nueve universidades del Foro con datos de simulación.
 *
 * - Nombres, siglas, sitios web, historia y NOMBRES DE PROGRAMAS son reales: se tomaron de la
 *   oferta publicada por cada universidad (sitios oficiales, septiembre 2026).
 * - Representantes, correos y biografías son FICTICIOS: nombres inventados y correos con dominio
 *   reservado `.test`, que nunca llega a un buzón real.
 * - Las fechas de ingreso al Foro son de simulación.
 */
import type { PhotoKey } from './media';

export type Level = 'Maestria' | 'Doctorado' | 'Especializacion' | 'Diplomado';
export type Modality = 'Presencial' | 'Virtual' | 'Hibrida';

export interface SeedProgram {
  name: string;
  level: Level;
  modality: Modality;
  duration: string;
  /** Facultad o unidad que lo imparte. */
  unit: string;
  /** Tres ejes del plan de estudios (se usan en la descripción). */
  focus: [string, string, string];
}

export interface SeedRepresentative {
  fullName: string;
  position: string;
  email: string;
  bio: string;
  /** Para el avatar: semilla estable. */
  seed: string;
}

export interface SeedUniversity {
  name: string;
  acronym: string;
  website: string;
  postgradUrl: string;
  joinedForumAt: string;
  founded: number;
  city: string;
  /** Colores del sello generado (primario, acento). */
  colors: [string, string];
  shortDescription: string;
  campusPhotos: PhotoKey[];
  representatives: SeedRepresentative[];
  programs: SeedProgram[];
}

export const UNIVERSITIES: SeedUniversity[] = [
  {
    name: 'Universidad de San Carlos de Guatemala',
    acronym: 'USAC',
    website: 'https://www.usac.edu.gt',
    postgradUrl: 'https://cgsep.usac.edu.gt/website/',
    joinedForumAt: '2008-06-12',
    founded: 1676,
    city: 'Ciudad de Guatemala',
    colors: ['#001d5e', '#c9a227'],
    shortDescription:
      'Fundada por Real Cédula el 31 de enero de 1676, es la única universidad estatal y autónoma del país. Su Sistema de Estudios de Postgrado reúne más de 300 maestrías y 48 doctorados en diez facultades, ocho escuelas no facultativas y una red de centros universitarios en los departamentos. Desde la Ciudad Universitaria, en la zona 12, forma a buena parte de los investigadores, docentes y funcionarios públicos de Guatemala.',
    campusPhotos: ['usac-campus', 'usac-biblioteca', 'usac-t10', 'usac-recursos', 'usac-mural'],
    representatives: [
      {
        fullName: 'Dra. María Fernanda Castillo Rodas',
        position: 'Directora de la Coordinadora General del Sistema de Estudios de Postgrado',
        email: 'mf.castillo@usac.test',
        bio: 'Doctora en Educación y profesora titular de la Facultad de Humanidades. Coordina la articulación de los programas de postgrado de las facultades y centros regionales, y representa a la USAC ante el Foro desde 2021.',
        seed: 'mfcastillo',
      },
      {
        fullName: 'M.Sc. Luis Alberto Pérez Morales',
        position: 'Coordinador de Evaluación y Acreditación de Postgrados',
        email: 'la.perez@usac.test',
        bio: 'Ingeniero industrial con maestría en Gestión de la Calidad. Lidera los procesos de autoevaluación de programas y el registro de estadísticas de postgrado.',
        seed: 'laperez',
      },
      {
        fullName: 'Licda. Ana Lucía Orellana Batres',
        position: 'Enlace de Investigación y Publicaciones',
        email: 'al.orellana@usac.test',
        bio: 'Especialista en comunicación científica. Acompaña a estudiantes de maestría y doctorado en la publicación de sus tesis en revistas indexadas.',
        seed: 'alorellana',
      },
    ],
    programs: [
      {
        name: 'Doctorado en Educación',
        level: 'Doctorado',
        modality: 'Presencial',
        duration: '3 años',
        unit: 'Facultad de Humanidades',
        focus: ['Epistemología de la educación', 'Política educativa', 'Investigación doctoral'],
      },
      {
        name: 'Doctorado en Salud Pública',
        level: 'Doctorado',
        modality: 'Hibrida',
        duration: '4 años',
        unit: 'Facultad de Ciencias Médicas',
        focus: ['Epidemiología avanzada', 'Sistemas de salud', 'Bioestadística'],
      },
      {
        name: 'Doctorado en Derecho',
        level: 'Doctorado',
        modality: 'Presencial',
        duration: '3 años',
        unit: 'Facultad de Ciencias Jurídicas y Sociales',
        focus: ['Teoría del derecho', 'Derecho constitucional comparado', 'Seminario de tesis'],
      },
      {
        name: 'Maestría en Docencia Universitaria',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Facultad de Humanidades',
        focus: ['Didáctica universitaria', 'Evaluación del aprendizaje', 'Diseño curricular'],
      },
      {
        name: 'Maestría en Administración Financiera',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Facultad de Ciencias Económicas',
        focus: ['Finanzas corporativas', 'Mercados de capitales', 'Gestión de riesgos'],
      },
      {
        name: 'Maestría en Gestión Industrial',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Facultad de Ingeniería',
        focus: ['Gestión de operaciones', 'Calidad y productividad', 'Cadena de suministro'],
      },
      {
        name: 'Maestría en Ingeniería Vial',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Facultad de Ingeniería',
        focus: ['Diseño geométrico de carreteras', 'Pavimentos', 'Seguridad vial'],
      },
      {
        name: 'Maestría en Energía y Ambiente',
        level: 'Maestria',
        modality: 'Hibrida',
        duration: '2 años',
        unit: 'Facultad de Ingeniería',
        focus: ['Energías renovables', 'Evaluación de impacto ambiental', 'Eficiencia energética'],
      },
      {
        name: 'Maestría en Ciencias Médicas con Especialidad en Pediatría',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '3 años',
        unit: 'Facultad de Ciencias Médicas',
        focus: ['Pediatría clínica', 'Neonatología', 'Investigación clínica'],
      },
      {
        name: 'Maestría en Gestión de la Calidad con Especialización en Inocuidad de Alimentos',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Facultad de Ciencias Químicas y Farmacia',
        focus: ['Sistemas HACCP', 'Microbiología de alimentos', 'Normativa sanitaria'],
      },
      {
        name: 'Maestría en Restauración de Monumentos',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Facultad de Arquitectura',
        focus: ['Patrimonio edificado', 'Técnicas de conservación', 'Centros históricos'],
      },
      {
        name: 'Maestría en Derecho Penal',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Facultad de Ciencias Jurídicas y Sociales',
        focus: ['Teoría del delito', 'Proceso penal acusatorio', 'Criminología'],
      },
      {
        name: 'Especialización en Gestión del Riesgo de Desastres',
        level: 'Especializacion',
        modality: 'Hibrida',
        duration: '1 año',
        unit: 'Escuela de Ciencia Política',
        focus: ['Análisis de amenazas', 'Planificación territorial', 'Respuesta y recuperación'],
      },
      {
        name: 'Diplomado en Metodología de la Investigación Científica',
        level: 'Diplomado',
        modality: 'Virtual',
        duration: '4 meses',
        unit: 'Coordinadora General del Sistema de Estudios de Postgrado',
        focus: ['Planteamiento del problema', 'Diseño metodológico', 'Redacción del protocolo'],
      },
    ],
  },
  {
    name: 'Universidad Rafael Landívar',
    acronym: 'URL',
    website: 'https://www.url.edu.gt',
    postgradUrl: 'https://principal.url.edu.gt/posgrados/',
    joinedForumAt: '2008-06-12',
    founded: 1961,
    city: 'Ciudad de Guatemala',
    colors: ['#150f5d', '#ffc61f'],
    shortDescription:
      'Universidad jesuita fundada en 1961, con Campus Central en Vista Hermosa III y campus y sedes en los principales departamentos del país. Ofrece más de 45 programas de posgrado —presenciales, híbridos y virtuales— en empresa, salud, ambiente, ciencias sociales, humanidades y teología, con convenios con más de quince universidades extranjeras. Forma profesionales conscientes, competentes, compasivos y comprometidos con la transformación de Guatemala.',
    campusPhotos: ['url-campus', 'url-biblioteca', 'url-capilla', 'url-tec'],
    representatives: [
      {
        fullName: 'Dr. José Ignacio Herrera Solís',
        position: 'Director de Posgrados',
        email: 'ji.herrera@url.test',
        bio: 'Doctor en Economía por una universidad jesuita española. Impulsó la oferta híbrida de posgrados de la Landívar y coordina las alianzas internacionales de doble titulación.',
        seed: 'jiherrera',
      },
      {
        fullName: 'M.A. Gabriela Sofía Monterroso Aldana',
        position: 'Coordinadora Académica de Maestrías',
        email: 'gs.monterroso@url.test',
        bio: 'Máster en Políticas Públicas. Acompaña el diseño curricular de nuevas maestrías y el seguimiento a egresados de posgrado.',
        seed: 'gsmonterroso',
      },
      {
        fullName: 'Lic. Andrés Eduardo Figueroa Lemus',
        position: 'Enlace de Movilidad Académica',
        email: 'ae.figueroa@url.test',
        bio: 'Gestiona los intercambios de docentes y estudiantes de posgrado con las universidades del Foro y con la red AUSJAL.',
        seed: 'aefigueroa',
      },
    ],
    programs: [
      {
        name: 'Doctorado en Economía',
        level: 'Doctorado',
        modality: 'Presencial',
        duration: '3 años',
        unit: 'Facultad de Ciencias Económicas y Empresariales',
        focus: ['Microeconomía avanzada', 'Econometría', 'Desarrollo económico'],
      },
      {
        name: 'Doctorado en Investigación Interdisciplinaria para la Transformación Social',
        level: 'Doctorado',
        modality: 'Hibrida',
        duration: '3 años',
        unit: 'Facultad de Humanidades',
        focus: ['Pensamiento crítico', 'Métodos mixtos', 'Incidencia social'],
      },
      {
        name: 'Doctorado en Derecho',
        level: 'Doctorado',
        modality: 'Presencial',
        duration: '3 años',
        unit: 'Facultad de Ciencias Jurídicas y Sociales',
        focus: ['Filosofía del derecho', 'Derechos fundamentales', 'Investigación jurídica'],
      },
      {
        name: 'Maestría en Administración de Empresas',
        level: 'Maestria',
        modality: 'Hibrida',
        duration: '2 años',
        unit: 'Facultad de Ciencias Económicas y Empresariales',
        focus: ['Dirección estratégica', 'Finanzas gerenciales', 'Liderazgo'],
      },
      {
        name: 'Maestría en Finanzas',
        level: 'Maestria',
        modality: 'Hibrida',
        duration: '2 años',
        unit: 'Facultad de Ciencias Económicas y Empresariales',
        focus: ['Valuación de empresas', 'Portafolios de inversión', 'Banca'],
      },
      {
        name: 'Maestría en Mercadeo e Innovación Estratégica',
        level: 'Maestria',
        modality: 'Hibrida',
        duration: '2 años',
        unit: 'Facultad de Ciencias Económicas y Empresariales',
        focus: ['Comportamiento del consumidor', 'Marca', 'Innovación de productos'],
      },
      {
        name: 'Maestría en Políticas Públicas y Gobierno Digital',
        level: 'Maestria',
        modality: 'Hibrida',
        duration: '2 años',
        unit: 'Facultad de Ciencias Políticas y Sociales',
        focus: ['Análisis político aplicado', 'Gobierno abierto', 'Evaluación de políticas'],
      },
      {
        name: 'Maestría en Derechos Humanos',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '2 años',
        unit: 'Facultad de Ciencias Jurídicas y Sociales',
        focus: ['Sistema interamericano', 'Justicia transicional', 'Litigio estratégico'],
      },
      {
        name: 'Maestría en Salud Pública con Énfasis en Epidemiología',
        level: 'Maestria',
        modality: 'Hibrida',
        duration: '2 años',
        unit: 'Facultad de Ciencias de la Salud',
        focus: ['Vigilancia epidemiológica', 'Bioestadística', 'Salud comunitaria'],
      },
      {
        name: 'Maestría en Gestión de Tecnologías de la Información',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '2 años',
        unit: 'Facultad de Ingeniería',
        focus: ['Gobierno de TI', 'Arquitectura empresarial', 'Transformación digital'],
      },
      {
        name: 'Maestría en Filosofía',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '2 años',
        unit: 'Facultad de Humanidades',
        focus: ['Ética', 'Filosofía política', 'Pensamiento latinoamericano'],
      },
      {
        name: 'Maestría en Pedagogía Social',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Facultad de Humanidades',
        focus: ['Educación popular', 'Intervención comunitaria', 'Evaluación de programas'],
      },
      {
        name: 'Maestría en Ciencias Forenses y Probática',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Facultad de Ciencias Jurídicas y Sociales',
        focus: ['Criminalística', 'Prueba pericial', 'Cadena de custodia'],
      },
      {
        name: 'Especialización en Ciberseguridad',
        level: 'Especializacion',
        modality: 'Virtual',
        duration: '1 año',
        unit: 'Facultad de Ingeniería',
        focus: ['Seguridad de redes', 'Gestión de incidentes', 'Hacking ético'],
      },
      {
        name: 'Especialización en Ciencia de Datos',
        level: 'Especializacion',
        modality: 'Virtual',
        duration: '1 año',
        unit: 'Facultad de Ingeniería',
        focus: ['Estadística aplicada', 'Aprendizaje automático', 'Visualización'],
      },
      {
        name: 'Especialización en Formulación y Evaluación de Proyectos',
        level: 'Especializacion',
        modality: 'Presencial',
        duration: '1 año',
        unit: 'Facultad de Ciencias Económicas y Empresariales',
        focus: ['Estudio de mercado', 'Evaluación financiera', 'Marco lógico'],
      },
    ],
  },
  {
    name: 'Universidad del Valle de Guatemala',
    acronym: 'UVG',
    website: 'https://www.uvg.edu.gt',
    postgradUrl: 'https://www.uvg.edu.gt',
    joinedForumAt: '2008-06-12',
    founded: 1966,
    city: 'Ciudad de Guatemala',
    colors: ['#078b45', '#93bb4e'],
    shortDescription:
      'Universidad privada, sin fines de lucro e independiente de actividades políticas y religiosas, fundada en 1966. Reconocida por su investigación en ciencia, tecnología y salud, tiene su campus central en la zona 15 y campus en el Altiplano (Sololá) y en el Sur (Escuintla). Sus maestrías combinan teoría y práctica en salud, negocios, educación, ambiente, energía y ciencia de datos, varias de ellas impartidas en inglés.',
    campusPhotos: ['guate-panorama', 'biblioteca-1'],
    representatives: [
      {
        fullName: 'Dra. Carla Isabel Méndez Arriola',
        position: 'Decana de Estudios de Posgrado',
        email: 'ci.mendez@uvg.test',
        bio: 'Doctora en Ciencias Biológicas con posdoctorado en epidemiología molecular. Dirige la estrategia de posgrados con enfoque en investigación aplicada.',
        seed: 'cimendez',
      },
      {
        fullName: 'Ing. Diego Alejandro Samayoa Cifuentes',
        position: 'Coordinador de Programas de Maestría',
        email: 'da.samayoa@uvg.test',
        bio: 'Ingeniero en ciencias de la computación con maestría en analítica de negocios. Coordina los programas en inglés de la Business and Management School.',
        seed: 'dasamayoa',
      },
      {
        fullName: 'M.Ed. Paola Andrea Girón Estrada',
        position: 'Coordinadora de Posgrados en Educación',
        email: 'pa.giron@uvg.test',
        bio: 'Especialista en currículo y tecnología educativa. Lidera los posgrados de un año orientados a docentes en servicio.',
        seed: 'pagiron',
      },
    ],
    programs: [
      {
        name: 'Maestría en Epidemiología',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Facultad de Ciencias y Humanidades',
        focus: ['Diseño de estudios', 'Bioestadística', 'Enfermedades transmisibles'],
      },
      {
        name: 'Maestría en Ciencias Farmacéuticas',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Facultad de Ciencias y Humanidades',
        focus: ['Tecnología farmacéutica', 'Control de calidad', 'Regulación'],
      },
      {
        name: 'Maestría en Tecnología de Alimentos y Gestión',
        level: 'Maestria',
        modality: 'Hibrida',
        duration: '2 años',
        unit: 'Facultad de Ingeniería',
        focus: ['Procesos de alimentos', 'Inocuidad', 'Gestión de plantas'],
      },
      {
        name: 'Maestría en Gestión Ambiental y Sostenibilidad',
        level: 'Maestria',
        modality: 'Hibrida',
        duration: '2 años',
        unit: 'Facultad de Ingeniería',
        focus: ['Economía circular', 'Gestión de cuencas', 'Huella de carbono'],
      },
      {
        name: 'Maestría en Tecnología y Sostenibilidad Energética',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Facultad de Ingeniería',
        focus: ['Sistemas fotovoltaicos', 'Redes eléctricas', 'Mercados de energía'],
      },
      {
        name: 'Maestría en Desarrollo (Descentralización y Poder Local)',
        level: 'Maestria',
        modality: 'Hibrida',
        duration: '2 años',
        unit: 'Facultad de Ciencias Sociales',
        focus: ['Gobiernos locales', 'Políticas para el desarrollo', 'Monitoreo y evaluación'],
      },
      {
        name: 'Maestría en Ciencias Actuariales y Financieras',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Business and Management School',
        focus: ['Matemática actuarial', 'Seguros', 'Modelos de riesgo'],
      },
      {
        name: 'Maestría en Medición, Evaluación e Investigación Educativas',
        level: 'Maestria',
        modality: 'Hibrida',
        duration: '2 años',
        unit: 'Facultad de Educación',
        focus: ['Psicometría', 'Evaluación de aprendizajes', 'Investigación educativa'],
      },
      {
        name: 'Maestría en Consejería Psicológica y Salud Mental',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Facultad de Ciencias Sociales',
        focus: ['Intervención en crisis', 'Psicoterapia breve', 'Salud mental comunitaria'],
      },
      {
        name: 'Master in Business Intelligence and Analytics',
        level: 'Maestria',
        modality: 'Hibrida',
        duration: '2 años',
        unit: 'Business and Management School',
        focus: ['Data warehousing', 'Machine learning for business', 'Storytelling with data'],
      },
      {
        name: 'Master in Supply Chain, Operations and Logistics',
        level: 'Maestria',
        modality: 'Hibrida',
        duration: '2 años',
        unit: 'Business and Management School',
        focus: ['Operations strategy', 'Logistics networks', 'Procurement'],
      },
      {
        name: 'Posgrado en Docencia Superior e Innovación',
        level: 'Especializacion',
        modality: 'Virtual',
        duration: '1 año',
        unit: 'Facultad de Educación',
        focus: ['Aprendizaje activo', 'Innovación pedagógica', 'Evaluación auténtica'],
      },
      {
        name: 'Posgrado en Tecnología Educativa',
        level: 'Especializacion',
        modality: 'Virtual',
        duration: '1 año',
        unit: 'Facultad de Educación',
        focus: ['Diseño instruccional', 'Entornos virtuales', 'Recursos digitales'],
      },
      {
        name: 'Posgrado en Currículo',
        level: 'Especializacion',
        modality: 'Hibrida',
        duration: '1 año',
        unit: 'Facultad de Educación',
        focus: ['Diseño por competencias', 'Planificación', 'Evaluación curricular'],
      },
    ],
  },
  {
    name: 'Universidad Mariano Gálvez de Guatemala',
    acronym: 'UMG',
    website: 'https://www.umg.edu.gt',
    postgradUrl: 'https://umg.edu.gt/posgrados/',
    joinedForumAt: '2008-06-12',
    founded: 1966,
    city: 'Ciudad de Guatemala',
    colors: ['#003168', '#a1252b'],
    shortDescription:
      'Primera universidad privada de inspiración cristiana evangélica del país, fundada en 1966. Desde su campus central en la Finca El Zapote, zona 2, y sus centros universitarios en casi todos los departamentos, ofrece maestrías, especialidades y doctorados en derecho, salud, enfermería, ingeniería, administración, psicología, educación y teología, en modalidades presencial, semipresencial y virtual.',
    campusPhotos: ['umg-edificio', 'umg-aulas', 'umg-interior'],
    representatives: [
      {
        fullName: 'Dr. Rolando Enrique Chacón Villatoro',
        position: 'Director de la Escuela de Posgrados',
        email: 're.chacon@umg.test',
        bio: 'Doctor en Derecho y catedrático de derecho constitucional. Dirige la oferta de maestrías y doctorados de la UMG y su ampliación a los centros universitarios.',
        seed: 'rechacon',
      },
      {
        fullName: 'Dra. Sandra Patricia Ruano de León',
        position: 'Coordinadora de Doctorados',
        email: 'sp.ruano@umg.test',
        bio: 'Doctora en Ciencias de Enfermería. Coordina los seminarios doctorales y el comité de ética de investigación de posgrado.',
        seed: 'spruano',
      },
      {
        fullName: 'Ing. Mario Estuardo Barrios Cano',
        position: 'Coordinador de Posgrados Virtuales',
        email: 'me.barrios@umg.test',
        bio: 'Ingeniero en sistemas con maestría en seguridad informática. Administra la plataforma virtual de las maestrías en línea.',
        seed: 'mebarrios',
      },
    ],
    programs: [
      {
        name: 'Doctorado en Ciencias de Enfermería',
        level: 'Doctorado',
        modality: 'Hibrida',
        duration: '3 años',
        unit: 'Facultad de Enfermería',
        focus: ['Teorías del cuidado', 'Investigación en enfermería', 'Gestión de servicios'],
      },
      {
        name: 'Doctorado en Educación para la Era Digital',
        level: 'Doctorado',
        modality: 'Hibrida',
        duration: '3 años',
        unit: 'Facultad de Humanidades',
        focus: ['Aprendizaje en red', 'Políticas digitales', 'Tesis doctoral'],
      },
      {
        name: 'Doctorado en Sociología de la Religión',
        level: 'Doctorado',
        modality: 'Presencial',
        duration: '3 años',
        unit: 'Facultad de Teología',
        focus: ['Religión y sociedad', 'Métodos cualitativos', 'Pluralismo religioso'],
      },
      {
        name: 'Maestría en Administración de Negocios con Especialidad en Finanzas de la Empresa',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Facultad de Ciencias de la Administración',
        focus: ['Estrategia empresarial', 'Finanzas corporativas', 'Evaluación de proyectos'],
      },
      {
        name: 'Maestría en Derecho Constitucional',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Facultad de Ciencias Jurídicas y Sociales',
        focus: ['Justicia constitucional', 'Amparo', 'Derechos humanos'],
      },
      {
        name: 'Maestría en Derecho Penal y Procesal Penal',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Facultad de Ciencias Jurídicas y Sociales',
        focus: ['Dogmática penal', 'Litigación oral', 'Política criminal'],
      },
      {
        name: 'Maestría en Criminalística con Enfoque Penal',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Facultad de Ciencias Criminológicas y Criminalísticas',
        focus: ['Escena del crimen', 'Balística', 'Dactiloscopia'],
      },
      {
        name: 'Maestría en Seguridad Informática',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '2 años',
        unit: 'Facultad de Ingeniería en Sistemas',
        focus: ['Criptografía', 'Seguridad en la nube', 'Auditoría de sistemas'],
      },
      {
        name: 'Maestría en Análisis Forense Informático',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '2 años',
        unit: 'Facultad de Ingeniería en Sistemas',
        focus: ['Evidencia digital', 'Análisis de malware', 'Peritaje informático'],
      },
      {
        name: 'Maestría en Neurociencias Aplicadas a la Psicología',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Facultad de Psicología',
        focus: ['Neuropsicología', 'Evaluación cognitiva', 'Neurodesarrollo'],
      },
      {
        name: 'Maestría en Educación Superior',
        level: 'Maestria',
        modality: 'Hibrida',
        duration: '2 años',
        unit: 'Facultad de Humanidades',
        focus: ['Gestión universitaria', 'Docencia', 'Calidad educativa'],
      },
      {
        name: 'Maestría en Gestión Pública con Especialidad en Políticas Públicas',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '2 años',
        unit: 'Escuela de Gestión Pública',
        focus: ['Ciclo de las políticas', 'Presupuesto público', 'Transparencia'],
      },
      {
        name: 'Maestría en Seguridad Industrial',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Facultad de Ingeniería, Matemática y Ciencias Físicas',
        focus: ['Higiene industrial', 'Prevención de riesgos', 'Normas ISO 45001'],
      },
      {
        name: 'Especialización en Energías Renovables',
        level: 'Especializacion',
        modality: 'Presencial',
        duration: '1 año',
        unit: 'Facultad de Ingeniería, Matemática y Ciencias Físicas',
        focus: ['Energía solar', 'Energía eólica', 'Diseño de sistemas'],
      },
      {
        name: 'Especialización en Ingeniería Estructural Asistida por Computadora',
        level: 'Especializacion',
        modality: 'Presencial',
        duration: '1 año',
        unit: 'Facultad de Ingeniería, Matemática y Ciencias Físicas',
        focus: [
          'Análisis estructural',
          'Diseño sismorresistente',
          'Modelado por elementos finitos',
        ],
      },
    ],
  },
  {
    name: 'Universidad del Istmo',
    acronym: 'UNIS',
    website: 'https://unis.edu.gt',
    postgradUrl: 'https://unis.edu.gt/maestrias-y-posgrados/',
    joinedForumAt: '2010-03-18',
    founded: 1997,
    city: 'Ciudad de Guatemala',
    colors: ['#540013', '#efa800'],
    shortDescription:
      'Universidad privada fundada en 1997, de inspiración cristiana y vocación humanista, con sede en la zona 10 y campus en Fraijanes. Su oferta de posgrado incluye el MBA y el Executive MBA de la UNIS Business School, maestrías en arquitectura, BIM, comunicación, ingeniería textil y genética biomédica, además de UNIS Virtual, con maestrías en línea en docencia, finanzas, ciberseguridad y neuropsicología.',
    campusPhotos: ['biblioteca-2', 'auditorio'],
    representatives: [
      {
        fullName: 'Dr. Francisco Javier Aguilar Ibarra',
        position: 'Vicerrector Académico y enlace de Posgrados',
        email: 'fj.aguilar@unis.test',
        bio: 'Doctor en Filosofía. Coordina la política de posgrados de las facultades y la oferta de UNIS Virtual.',
        seed: 'fjaguilar',
      },
      {
        fullName: 'M.B.A. Lucía Beatriz Toledo Sandoval',
        position: 'Directora de Programas, UNIS Business School',
        email: 'lb.toledo@unis.test',
        bio: 'Especialista en dirección de empresas familiares. Dirige el MBA y el Executive MBA desde el campus de Fraijanes.',
        seed: 'lbtoledo',
      },
      {
        fullName: 'Arq. Rodrigo Alejandro Paz Velásquez',
        position: 'Coordinador de Maestrías de Arquitectura y Diseño',
        email: 'ra.paz@unis.test',
        bio: 'Arquitecto con maestría en gestión BIM. Coordina las maestrías híbridas de la Facultad de Arquitectura y Diseño.',
        seed: 'rapaz',
      },
    ],
    programs: [
      {
        name: 'Executive MBA',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'UNIS Business School',
        focus: ['Dirección general', 'Casos de negocio', 'Gobierno corporativo'],
      },
      {
        name: 'MBA',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'UNIS Business School',
        focus: ['Dirección comercial', 'Finanzas', 'Operaciones'],
      },
      {
        name: 'Maestría en Arquitectura con Especialidad',
        level: 'Maestria',
        modality: 'Hibrida',
        duration: '2 años',
        unit: 'Facultad de Arquitectura y Diseño',
        focus: ['Proyecto arquitectónico', 'Sostenibilidad', 'Paisaje urbano'],
      },
      {
        name: 'Maestría en Dirección de Empresas Constructoras e Inmobiliarias',
        level: 'Maestria',
        modality: 'Hibrida',
        duration: '2 años',
        unit: 'Facultad de Arquitectura y Diseño',
        focus: ['Desarrollo inmobiliario', 'Gestión de obra', 'Finanzas del proyecto'],
      },
      {
        name: 'Maestría en Building Information Modeling (BIM) Management',
        level: 'Maestria',
        modality: 'Hibrida',
        duration: '18 meses',
        unit: 'Facultad de Arquitectura y Diseño',
        focus: ['Modelado BIM', 'Coordinación de proyectos', 'Estándares ISO 19650'],
      },
      {
        name: 'Máster en Comunicación Estratégica y Reputación',
        level: 'Maestria',
        modality: 'Hibrida',
        duration: '18 meses',
        unit: 'Facultad de Comunicación',
        focus: ['Gestión de marca', 'Comunicación de crisis', 'Relaciones institucionales'],
      },
      {
        name: 'Maestría en Ingeniería Textil',
        level: 'Maestria',
        modality: 'Hibrida',
        duration: '2 años',
        unit: 'Facultad de Ingeniería',
        focus: ['Materiales textiles', 'Procesos de confección', 'Calidad'],
      },
      {
        name: 'Maestría en Ciencias en Genética Biomédica',
        level: 'Maestria',
        modality: 'Hibrida',
        duration: '2 años',
        unit: 'Facultad de Ciencias de la Salud',
        focus: ['Genética clínica', 'Genómica', 'Asesoría genética'],
      },
      {
        name: 'Maestría en Docencia Universitaria',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '18 meses',
        unit: 'UNIS Virtual',
        focus: ['Planificación docente', 'Evaluación', 'Tecnología educativa'],
      },
      {
        name: 'Maestría en Neuropsicología Clínica',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '18 meses',
        unit: 'UNIS Virtual',
        focus: ['Evaluación neuropsicológica', 'Rehabilitación cognitiva', 'Neuroanatomía'],
      },
      {
        name: 'Maestría en Ciberseguridad',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '18 meses',
        unit: 'UNIS Virtual',
        focus: ['Seguridad ofensiva', 'Gestión de riesgos', 'Continuidad del negocio'],
      },
      {
        name: 'Posgrado en Biología Molecular y Genética',
        level: 'Especializacion',
        modality: 'Hibrida',
        duration: '1 año',
        unit: 'Facultad de Ciencias de la Salud',
        focus: ['Técnicas moleculares', 'PCR y secuenciación', 'Bioinformática básica'],
      },
      {
        name: 'Posgrado en Farmacovigilancia',
        level: 'Especializacion',
        modality: 'Virtual',
        duration: '1 año',
        unit: 'Facultad de Ciencias de la Salud',
        focus: ['Reacciones adversas', 'Regulación sanitaria', 'Gestión de señales'],
      },
      {
        name: 'Posgrado en Derecho Corporativo y Tributario',
        level: 'Especializacion',
        modality: 'Presencial',
        duration: '1 año',
        unit: 'Facultad de Derecho',
        focus: ['Sociedades mercantiles', 'Planificación fiscal', 'Contratos'],
      },
      {
        name: 'Desarrollo de Herramientas Directivas',
        level: 'Diplomado',
        modality: 'Presencial',
        duration: '5 meses',
        unit: 'UNIS Business School',
        focus: ['Toma de decisiones', 'Negociación', 'Dirección de personas'],
      },
    ],
  },
  {
    name: 'Universidad Panamericana',
    acronym: 'UPANA',
    website: 'https://www.upana.edu.gt',
    postgradUrl: 'https://www.upana.edu.gt/maestrias/',
    joinedForumAt: '2012-08-23',
    founded: 1998,
    city: 'Ciudad de Guatemala',
    colors: ['#001b42', '#9fd140'],
    shortDescription:
      'Universidad privada de valores cristianos autorizada en 1998. Con trece campus propios y más de cien sedes en todo el país, reúne a más de 20 000 estudiantes. Ofrece maestrías en ciencias económicas, derecho, humanidades, salud, odontología y teología, y una línea virtual con Euroinnova en inteligencia artificial, big data, ciberseguridad y educación, pensadas para quien trabaja y estudia a la vez.',
    campusPhotos: ['guate-panorama-2', 'conferencia-2'],
    representatives: [
      {
        fullName: 'Dra. Julia Esperanza Cabrera Marroquín',
        position: 'Directora de Estudios de Posgrado',
        email: 'je.cabrera@upana.test',
        bio: 'Doctora en Educación con experiencia en gestión de sedes regionales. Coordina la oferta de maestrías en los trece campus.',
        seed: 'jecabrera',
      },
      {
        fullName: 'M.Sc. Óscar Leonel Tejada Ramírez',
        position: 'Coordinador de Maestrías en Ciencias Económicas',
        email: 'ol.tejada@upana.test',
        bio: 'Economista con maestría en economía aplicada. Coordina los programas de gestión financiera, tributaria y de talento humano.',
        seed: 'oltejada',
      },
      {
        fullName: 'Licda. Karla Vanessa Ordóñez Pineda',
        position: 'Coordinadora de UPANA Virtual',
        email: 'kv.ordonez@upana.test',
        bio: 'Especialista en educación en línea. Lidera la oferta virtual desarrollada en alianza con Euroinnova.',
        seed: 'kvordonez',
      },
    ],
    programs: [
      {
        name: 'Maestría en Business Management',
        level: 'Maestria',
        modality: 'Hibrida',
        duration: '2 años',
        unit: 'Facultad de Ciencias Económicas',
        focus: ['Gerencia estratégica', 'Innovación', 'Negocios globales'],
      },
      {
        name: 'Maestría en Consultoría Tributaria',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Facultad de Ciencias Económicas',
        focus: ['Legislación tributaria', 'Planificación fiscal', 'Defensa tributaria'],
      },
      {
        name: 'Maestría en Economía Aplicada',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Facultad de Ciencias Económicas',
        focus: ['Econometría aplicada', 'Economía del desarrollo', 'Política económica'],
      },
      {
        name: 'Maestría en Gestión del Talento Humano',
        level: 'Maestria',
        modality: 'Hibrida',
        duration: '2 años',
        unit: 'Facultad de Ciencias Económicas',
        focus: ['Gestión por competencias', 'Clima organizacional', 'Compensaciones'],
      },
      {
        name: 'Maestría en Derecho Procesal',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Facultad de Ciencias Jurídicas y Justicia',
        focus: ['Teoría general del proceso', 'Oralidad', 'Recursos'],
      },
      {
        name: 'Maestría en Psicoterapia Infantil',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Facultad de Humanidades',
        focus: ['Desarrollo infantil', 'Terapia de juego', 'Trabajo con familias'],
      },
      {
        name: 'Maestría en Movilidad Humana y Desarrollo con Enfoque en Derechos Humanos',
        level: 'Maestria',
        modality: 'Hibrida',
        duration: '2 años',
        unit: 'Facultad de Humanidades',
        focus: ['Migración y desarrollo', 'Protección internacional', 'Reintegración'],
      },
      {
        name: 'Maestría en Salud y Seguridad Ocupacional',
        level: 'Maestria',
        modality: 'Hibrida',
        duration: '2 años',
        unit: 'Facultad de Ciencias Médicas y de la Salud',
        focus: ['Ergonomía', 'Toxicología laboral', 'Vigilancia de la salud'],
      },
      {
        name: 'Maestría en Endodoncia',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Facultad de Odontología',
        focus: ['Terapia pulpar', 'Microcirugía endodóntica', 'Traumatología dental'],
      },
      {
        name: 'Maestría en Teología Sistemática',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Facultad de Teología',
        focus: ['Dogmática', 'Hermenéutica', 'Teología contemporánea'],
      },
      {
        name: 'Maestría en Inteligencia Artificial',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '15 meses',
        unit: 'UPANA Virtual',
        focus: ['Aprendizaje automático', 'Redes neuronales', 'Ética de la IA'],
      },
      {
        name: 'Maestría en Ciberseguridad y Hacking Ético',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '15 meses',
        unit: 'UPANA Virtual',
        focus: ['Pruebas de penetración', 'Seguridad de aplicaciones', 'Respuesta a incidentes'],
      },
      {
        name: 'Diplomado en Docencia Universitaria',
        level: 'Diplomado',
        modality: 'Virtual',
        duration: '4 meses',
        unit: 'Facultad de Humanidades',
        focus: ['Planificación didáctica', 'Evaluación', 'Aula invertida'],
      },
    ],
  },
  {
    name: 'Universidad Mesoamericana',
    acronym: 'UMES',
    website: 'https://www.umes.edu.gt',
    postgradUrl: 'https://www.umes.edu.gt/isel-umes',
    joinedForumAt: '2014-05-29',
    founded: 1999,
    city: 'Quetzaltenango',
    colors: ['#0a4735', '#e6deca'],
    shortDescription:
      'Universidad privada de identidad salesiana, fundada en 1999 y parte de la red de Instituciones Salesianas de Educación Superior. Tiene sedes en la Ciudad de Guatemala, Quetzaltenango —la más grande—, Alta Verapaz e Izabal. Su Instituto Salesiano de Educación en Línea (ISEL) ofrece maestrías 100 % en línea en inteligencia de negocios, fintech, marketing digital, talento humano e innovación educativa.',
    campusPhotos: ['umes-frente', 'umes-edificio', 'umes-aulas', 'xela-parque'],
    representatives: [
      {
        fullName: 'P. Carlos Humberto Chávez Lima, SDB',
        position: 'Vicerrector Académico',
        email: 'ch.chavez@umes.test',
        bio: 'Sacerdote salesiano y doctor en Ciencias de la Educación. Coordina la oferta académica de las cuatro sedes y representa a la UMES en el Foro.',
        seed: 'chchavez',
      },
      {
        fullName: 'M.A. Ingrid Maritza López Recinos',
        position: 'Directora del ISEL (Instituto Salesiano de Educación en Línea)',
        email: 'im.lopez@umes.test',
        bio: 'Máster en innovación educativa. Dirige las maestrías en línea y la formación de tutores virtuales.',
        seed: 'imlopez',
      },
      {
        fullName: 'Lic. Byron Estuardo Ajú Coyoy',
        position: 'Coordinador de Posgrados, sede Quetzaltenango',
        email: 'be.aju@umes.test',
        bio: 'Administrador de empresas con maestría en auditoría. Coordina los programas presenciales en occidente y el vínculo con el sector productivo de Quetzaltenango.',
        seed: 'beaju',
      },
    ],
    programs: [
      {
        name: 'Maestría en Innovación de los Aprendizajes en la Educación Superior',
        level: 'Maestria',
        modality: 'Hibrida',
        duration: '2 años',
        unit: 'Instituto Salesiano de Educación en Línea',
        focus: ['Aprendizaje significativo', 'Didáctica digital', 'Pedagogía salesiana'],
      },
      {
        name: 'Maestría en Administración de Empresas e Inteligencia de Negocios',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '2 años',
        unit: 'Instituto Salesiano de Educación en Línea',
        focus: ['Gestión estratégica', 'Tableros de control', 'Análisis de datos'],
      },
      {
        name: 'Maestría en Marketing Digital y Comercio Electrónico',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '2 años',
        unit: 'Instituto Salesiano de Educación en Línea',
        focus: ['Estrategia digital', 'Comercio electrónico', 'Analítica web'],
      },
      {
        name: 'Maestría en Administración de Empresas con Especialidad en Finanzas y Tecnología (FINTECH)',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '2 años',
        unit: 'Instituto Salesiano de Educación en Línea',
        focus: ['Finanzas digitales', 'Pagos y blockchain', 'Regulación fintech'],
      },
      {
        name: 'Maestría en Gestión Estratégica del Talento Humano',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '2 años',
        unit: 'Instituto Salesiano de Educación en Línea',
        focus: ['Gestión del cambio', 'Desarrollo organizacional', 'Bienestar laboral'],
      },
      {
        name: 'Maestría en Auditoría de Desempeño',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Facultad de Ciencias Económicas',
        focus: ['Auditoría gubernamental', 'Indicadores de gestión', 'Control interno'],
      },
      {
        name: 'Diplomado en Metodología de la Investigación',
        level: 'Diplomado',
        modality: 'Virtual',
        duration: '3 meses',
        unit: 'Dirección de Investigación',
        focus: ['Pregunta de investigación', 'Revisión de literatura', 'Normas APA'],
      },
      {
        name: 'Diplomado en Gestión de Proyectos Sociales',
        level: 'Diplomado',
        modality: 'Presencial',
        duration: '4 meses',
        unit: 'Sede Quetzaltenango',
        focus: ['Diagnóstico comunitario', 'Marco lógico', 'Sostenibilidad'],
      },
    ],
  },
  {
    name: 'Universidad Galileo',
    acronym: 'Galileo',
    website: 'https://www.galileo.edu',
    postgradUrl: 'https://www.galileo.edu',
    joinedForumAt: '2011-09-15',
    founded: 2000,
    city: 'Ciudad de Guatemala',
    colors: ['#041b64', '#b89a59'],
    shortDescription:
      'Universidad privada autorizada en el año 2000, heredera de la tradición tecnológica de la Facultad de Ingeniería de Sistemas, Informática y Ciencias de la Computación. Con campus central en la zona 10, ofrece más de 120 especializaciones de posgrado y maestría y siete doctorados, con programas en alianza con el MIT, y una fuerte oferta virtual en ciencia de datos, ciberseguridad, energía, salud y educación.',
    campusPhotos: ['galileo-campus', 'galileo-frente', 'galileo-aulas'],
    representatives: [
      {
        fullName: 'Dr. Héctor Manuel Rivas Quiñónez',
        position: 'Director de Estudios de Posgrado',
        email: 'hm.rivas@galileo.test',
        bio: 'Doctor en Ingeniería Industrial. Coordina las maestrías de la Facultad de Ciencia, Tecnología e Industria y los programas en alianza con el MIT.',
        seed: 'hmrivas',
      },
      {
        fullName: 'Dra. Mónica Alejandra Fuentes Pellecer',
        position: 'Directora del Instituto de Investigación de Operaciones',
        email: 'ma.fuentes@galileo.test',
        bio: 'Doctora en estadística aplicada. Dirige las maestrías en Data Science y Business Intelligence y Analytics.',
        seed: 'mafuentes',
      },
      {
        fullName: 'Ing. Walter René Soto Barillas',
        position: 'Coordinador de Posgrados Virtuales, Instituto Von Neumann',
        email: 'wr.soto@galileo.test',
        bio: 'Especialista en e-learning. Coordina la producción de cursos y la experiencia de estudiantes en línea.',
        seed: 'wrsoto',
      },
    ],
    programs: [
      {
        name: 'Doctorado en Desarrollo Sostenible',
        level: 'Doctorado',
        modality: 'Hibrida',
        duration: '3 años',
        unit: 'Instituto en Desarrollo Sostenible',
        focus: ['Economía ecológica', 'Gobernanza ambiental', 'Investigación doctoral'],
      },
      {
        name: 'Doctorado en Ingeniería Industrial',
        level: 'Doctorado',
        modality: 'Presencial',
        duration: '3 años',
        unit: 'Facultad de Ciencia, Tecnología e Industria',
        focus: ['Optimización', 'Sistemas de producción', 'Tesis doctoral'],
      },
      {
        name: 'Doctorado en Administración Pública y Políticas Públicas',
        level: 'Doctorado',
        modality: 'Hibrida',
        duration: '3 años',
        unit: 'Facultad de Ciencia, Tecnología e Industria',
        focus: [
          'Teoría de la administración pública',
          'Evaluación de políticas',
          'Gestión por resultados',
        ],
      },
      {
        name: 'Maestría en Ciberseguridad',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '2 años',
        unit: 'Facultad de Ingeniería de Sistemas, Informática y Ciencias de la Computación',
        focus: ['Seguridad ofensiva y defensiva', 'Gobierno de la seguridad', 'Forense digital'],
      },
      {
        name: 'Maestría en Data Science',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '2 años',
        unit: 'Instituto en Investigación de Operaciones',
        focus: ['Estadística computacional', 'Aprendizaje profundo', 'Big data'],
      },
      {
        name: 'Maestría en Business Intelligence y Analytics',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '2 años',
        unit: 'Instituto en Investigación de Operaciones',
        focus: ['Modelado de datos', 'Visualización', 'Analítica predictiva'],
      },
      {
        name: 'Maestría en Ingeniería Biomédica',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Facultad de Ingeniería de Sistemas, Informática y Ciencias de la Computación',
        focus: [
          'Instrumentación médica',
          'Procesamiento de señales',
          'Gestión de tecnología hospitalaria',
        ],
      },
      {
        name: 'Maestría en Energía Renovable',
        level: 'Maestria',
        modality: 'Hibrida',
        duration: '2 años',
        unit: 'Instituto de Recursos Energéticos',
        focus: ['Hidroenergía', 'Solar y eólica', 'Regulación energética'],
      },
      {
        name: 'Maestría en Administración Hospitalaria',
        level: 'Maestria',
        modality: 'Hibrida',
        duration: '2 años',
        unit: 'Facultad de Biología, Química y Farmacia',
        focus: ['Gestión hospitalaria', 'Calidad en salud', 'Finanzas de la salud'],
      },
      {
        name: 'Maestría en Medicina Familiar',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '3 años',
        unit: 'Facultad de Ciencias de la Salud',
        focus: ['Atención primaria', 'Medicina preventiva', 'Salud comunitaria'],
      },
      {
        name: 'Maestría en Criminalística y Criminología',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Instituto de Estudios en Seguridad',
        focus: ['Investigación criminal', 'Victimología', 'Prevención del delito'],
      },
      {
        name: 'Maestría en Dirección y Producción de e-Learning',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '2 años',
        unit: 'Instituto Von Neumann',
        focus: ['Diseño instruccional', 'Producción multimedia', 'Gestión de campus virtuales'],
      },
      {
        name: 'Maestría en Diplomacia y Relaciones Internacionales',
        level: 'Maestria',
        modality: 'Presencial',
        duration: '2 años',
        unit: 'Escuela Superior de Diplomacia y Relaciones Internacionales',
        focus: ['Derecho internacional', 'Negociación', 'Geopolítica'],
      },
      {
        name: 'Postgrado en Análisis y Predicción de Datos',
        level: 'Especializacion',
        modality: 'Virtual',
        duration: '1 año',
        unit: 'Instituto en Investigación de Operaciones',
        focus: ['Series de tiempo', 'Modelos predictivos', 'Python para análisis'],
      },
      {
        name: 'Postgrado en Medicina de Emergencias',
        level: 'Especializacion',
        modality: 'Presencial',
        duration: '1 año',
        unit: 'Facultad de Ciencias de la Salud',
        focus: ['Soporte vital avanzado', 'Trauma', 'Toxicología de urgencia'],
      },
      {
        name: 'Postgrado en Eficiencia Energética',
        level: 'Especializacion',
        modality: 'Virtual',
        duration: '1 año',
        unit: 'Instituto de Recursos Energéticos',
        focus: ['Auditoría energética', 'Edificaciones eficientes', 'Normativa'],
      },
    ],
  },
  {
    name: 'Universidad InterNaciones',
    acronym: 'UNI',
    website: 'https://uni.edu.gt',
    postgradUrl: 'https://uni.edu.gt/maestrias/',
    joinedForumAt: '2019-11-07',
    founded: 2011,
    city: 'Ciudad de Guatemala',
    colors: ['#006c8f', '#ee6946'],
    shortDescription:
      'Universidad guatemalteca de educación superior en línea, con más de cuarenta maestrías oficiales de vocación internacional en ingeniería y tecnología, ciencias económicas y empresariales, salud y educación. Sus programas de uno a dos años se cursan 100 % en línea y se sostienen en un proyecto de responsabilidad social que ofrece becas amplias a colectivos vulnerables y a profesionales del sector público.',
    campusPhotos: ['participantes', 'panel-2'],
    representatives: [
      {
        fullName: 'Dr. Ernesto Joaquín Vela Montenegro',
        position: 'Rector y representante ante el Foro',
        email: 'ej.vela@uni.test',
        bio: 'Doctor en Tecnología Educativa. Impulsa la educación superior en línea como vía de acceso para profesionales de todo el país.',
        seed: 'ejvela',
      },
      {
        fullName: 'M.Sc. Daniela Beatriz Arévalo Chew',
        position: 'Directora Académica de Maestrías',
        email: 'db.arevalo@uni.test',
        bio: 'Máster en dirección de proyectos. Supervisa la calidad académica y la acreditación internacional de las maestrías en línea.',
        seed: 'dbarevalo',
      },
      {
        fullName: 'Lic. Santiago Rafael Ixcot Menchú',
        position: 'Coordinador de Becas y Proyección Social',
        email: 'sr.ixcot@uni.test',
        bio: 'Coordina el programa de becas de entre 90 y 100 % para colectivos vulnerables y servidores públicos.',
        seed: 'srixcot',
      },
    ],
    programs: [
      {
        name: 'Maestría Internacional en Inteligencia Artificial',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '15 meses',
        unit: 'Facultad de Ingeniería, Ciencia, Arte y Tecnología',
        focus: [
          'Aprendizaje automático',
          'Procesamiento de lenguaje natural',
          'Visión por computadora',
        ],
      },
      {
        name: 'Maestría Internacional en Ciberseguridad',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '15 meses',
        unit: 'Facultad de Ingeniería, Ciencia, Arte y Tecnología',
        focus: ['Seguridad de la información', 'Hacking ético', 'Normativa y cumplimiento'],
      },
      {
        name: 'Maestría Internacional en Análisis y Visualización de Datos Masivos – Big Data',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '15 meses',
        unit: 'Facultad de Ingeniería, Ciencia, Arte y Tecnología',
        focus: ['Ecosistema Hadoop y Spark', 'Bases de datos NoSQL', 'Visualización'],
      },
      {
        name: 'Maestría Internacional en Industria 4.0',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '15 meses',
        unit: 'Facultad de Ingeniería, Ciencia, Arte y Tecnología',
        focus: ['Internet de las cosas', 'Automatización', 'Gemelos digitales'],
      },
      {
        name: 'Maestría en Ingeniería Sanitaria',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '18 meses',
        unit: 'Facultad de Ingeniería, Ciencia, Arte y Tecnología',
        focus: ['Agua potable', 'Tratamiento de aguas residuales', 'Residuos sólidos'],
      },
      {
        name: 'Maestría Internacional en Administración de Empresas (MBA)',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '15 meses',
        unit: 'Facultad de Ciencias Económicas y Empresariales',
        focus: ['Dirección estratégica', 'Finanzas', 'Marketing'],
      },
      {
        name: 'Maestría Internacional en Marketing Digital',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '12 meses',
        unit: 'Facultad de Ciencias Económicas y Empresariales',
        focus: ['SEO y SEM', 'Redes sociales', 'Analítica digital'],
      },
      {
        name: 'Maestría en Normas Internacionales de Información Financiera (NIIF)',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '15 meses',
        unit: 'Facultad de Ciencias Económicas y Empresariales',
        focus: ['NIIF plenas', 'NIIF para pymes', 'Consolidación de estados financieros'],
      },
      {
        name: 'Maestría en Auditoría Interna Gubernamental',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '15 meses',
        unit: 'Facultad de Ciencias Económicas y Empresariales',
        focus: ['Control gubernamental', 'Auditoría basada en riesgos', 'Probidad'],
      },
      {
        name: 'Maestría en Dirección y Administración en Salud',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '15 meses',
        unit: 'Facultad de Ciencias de la Salud',
        focus: ['Gestión de servicios de salud', 'Economía de la salud', 'Calidad asistencial'],
      },
      {
        name: 'Maestría en Intervención Psicológica en Niños y Adolescentes',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '15 meses',
        unit: 'Facultad de Ciencias de la Salud',
        focus: [
          'Evaluación infantojuvenil',
          'Terapia cognitivo-conductual',
          'Trabajo con familias',
        ],
      },
      {
        name: 'Maestría Internacional en Docencia Universitaria',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '12 meses',
        unit: 'Facultad de Ciencias de la Educación y Humanidades',
        focus: ['Didáctica universitaria', 'Evaluación por competencias', 'Docencia en línea'],
      },
      {
        name: 'Maestría Internacional en Liderazgo y Dirección de Centros Educativos',
        level: 'Maestria',
        modality: 'Virtual',
        duration: '12 meses',
        unit: 'Facultad de Ciencias de la Educación y Humanidades',
        focus: ['Liderazgo pedagógico', 'Gestión escolar', 'Convivencia'],
      },
    ],
  },
];
